### ISSUE TITLE
pathetic

### ISSUE THREAD

**Issue by cahekska** [EurekaEffect/LmaoBox-crack#2]
эх, сейчас бы дублировать уже существующие репозитории.... Спасибо, что волнуешься за ретардов которые не в состоянии найти то же самое на акке ваймера🥰

**Comment by EurekaEffect** [comment]
> эх, сейчас бы дублировать уже существующие репозитории.... Спасибо, что волнуешься за ретардов которые не в состоянии найти то же самое на акке ваймера🥰

скопировал с прошлого иссуе

"meteordevelopment.addons.bookdupe.BookDupeAddon" -> "lmaobox.LmaoBoxGetGoodChangeYourGamesenseAndNeverLoseByJackesparragosAndMore" (без этого кстати аддон вообще не отображается в майне)
обнова на 1.18, обновление на новые зависимости метеора и в мейн классе другой импорт MeteorAddon
ImprovedAutoCity не имеет нормального окончания блока https://cdn.discordapp.com/attachments/834495397983551538/924387026260885556/unknown.png
удалил бесполезный пекедж метеор темплейта, вместе с букдюпом (бесполезный + не инициализируется в аддоне)

найди еще к чему доебаться, книгтум)

**Comment by cahekska** [comment]
а смысл от этих действий? Ваймер выложил код, полученный от автора. Тот, кому реально захочется засорить себе метеор бесполезными функциями, а не спиздить часть(хотя тут нечего пиздить), сам поставит те полторы точки с запятой, уберет/доделает автосити и забилдит. Ты лишь спиздил готовое, потратил пару минут на "охуеть какие полезные действия", и теперь ты такой весь из себя крутой, к твоей коллекции слитых скидов добавился еще один скид. Молодец че, иди еще сортирах у крафтера спизди, ну или если тебе совсем нечего делать, скопируй у crystallinqq фобос))))
